firstno=input("Enter the first number:")
secondno=input("Enter the second number:")
addition=int(firstno)+int(secondno)
subtraction=int(firstno)-int(secondno)
multiplication=int(firstno)*int(secondno)
division=int(firstno)/int(secondno)
print("Addition:",addition)
print("Subtraction:",subtraction)
print("Multiplication:",multiplication)
print("Division:",division)
